---
title: "austin crime interactive"
author: "@nntrn"
date: "11/6/2018"
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
runtime: shiny_prerendered
---

```{r, context="setup", include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

my_theme <- theme_minimal() +
  theme(
    axis.text.x = element_text(colour = "grey20", size = 13, face = "bold"),
    axis.text.y = element_text(colour = "grey20", size = 13, face = "bold"),
   legend.position="bottom", legend.box = "horizontal"
  )

theme_set(my_theme)


p <- read_csv("/Users/annie/programming-notes/R/austin-crime/output/p.csv")
p$month <- ordered(p$month, toupper(month.abb))

p2 <- p %>%
    filter(street_name != "UNKNOWN") %>%
    group_by(highest_offense_description, street_name) %>%
    summarise(n = n(), s = sum(value)) %>%
    arrange(desc(n))


p_list <- p2 %>%
    group_by(highest_offense_description) %>%
    summarise(n = n()) %>%
    arrange(desc(n)) 

zip <- p%>%
    group_by(zip_code) %>%
    summarise(n = n()) %>%
    na.omit() %>%
    arrange(desc(n))
```



```{r, context="render", echo=FALSE}


  selectInput("zipcode", label = "select zip", multiple = TRUE,
              choices = zip$zip_code, selected = "78757")
  
   radioButtons("category", label = "select offense category", inline = TRUE,
              choices = na.omit(unique(p$category_description)))
  
plotOutput("distPlot")
```


```{r, context="server"}

output$distPlot <- renderPlot({
  zip_string <- gsub(", ", " AND ", toString(input$zipcode))

  g1 <- p %>%
    filter(
      zip_code == input$zipcode,
      category_description == input$category
    ) %>%
    group_by(zip_code, month) %>%
    summarise(n = n(), s = sum(value)) %>%
    ggplot(aes(month, s, color = as.character(zip_code))) +
    geom_point(size = 3, alpha = 1) +
    labs(
      x = "",
      y = "",
      colour = "zipcode",
      title = paste("2017 CRIME DATA FOR ", toupper(input$category), " IN ", zip_string)
    )
  g1
})

```

